### ISSUE TITLE
[Forge] Holding a light source in your hand does not affect contraption lighting.

### ISSUE THREAD

**Issue by Fokke456** [leon-o/Create-Dynamic-Lights#5]
**Description**
On forge 1.20.1, with just Create, Create Dynamic Lights, and Rubidium Dynamic Lights, contraptions are not lit by light sources in the player's hand:
![2024-08-26_20 12 58](https://github.com/user-attachments/assets/ac27e9f6-f725-4b84-a90a-3077dd0b970f)
Light sources in contraptions seem to behave as they ought.

**Expected behavior**
Contraptions are affected by outside handheld sources of light 

**Log**
[Here.](https://github.com/user-attachments/files/16752395/log.txt)

**Comment by leon-o** [comment]
This mod is designed to allow contraptions to generate light to illuminate surrounding blocks, rather than to ensure that other light sources, such as those held in the player's hand, can illuminate the contraption. Thus, the behavior you're experiencing aligns with the mod's intended functionality.

In short, the mod does not currently support the feature of allowing light sources held by players to affect the lighting of contraptions. We also do not have plans to add this feature at this time, as it could increase the complexity of the mod and potentially impact performance.

Anyway, if you have any further questions or suggestions, please feel free to continue the discussion.
